# Generated by Django 4.0.5 on 2022-06-22 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='상품 명')),
                ('content', models.TextField(verbose_name='상품 설명')),
                ('thumbnail', models.ImageField(upload_to='product/img', verbose_name='썸네일')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='수정 일자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일자')),
                ('show_end_at', models.DateTimeField(default='2022-06-25 00:00:00', verbose_name='노출 종료 일자')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
