# Generated by Django 4.0.5 on 2022-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='show_end_at',
            field=models.DateTimeField(default='2022-06-25 00:00:00'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_start_at',
            field=models.DateTimeField(default='2022-06-20 00:00:00'),
        ),
    ]
