# Generated by Django 4.0.5 on 2022-06-21 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 13, 24, 35, 969565), verbose_name='노출 종료 일자'),
        ),
    ]
