# Generated by Django 4.0.5 on 2022-06-21 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_show_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 13, 30, 28, 819787), verbose_name='노출 종료 일자'),
        ),
    ]
