# Generated by Django 4.0.5 on 2022-06-21 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_show_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='show_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 8, 55, 52, 934702, tzinfo=utc), verbose_name='노출 종료 일자'),
        ),
    ]
