# Generated by Django 4.0.5 on 2022-06-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userporfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPorfile',
            new_name='UserProfile',
        ),
    ]
