# Generated by Django 4.0.5 on 2022-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_userporfile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=10)),
                ('userprofile', models.ManyToManyField(related_name='hobby', to='user.userprofile')),
            ],
        ),
    ]
