# Generated by Django 4.0.5 on 2022-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='userprofile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='interest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(related_name='userprofile', to='user.hobby'),
        ),
    ]
