# Generated by Django 4.0.5 on 2022-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_hobby_userprofile_remove_userprofile_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(to='user.hobby'),
        ),
    ]
